

services:
  clickhouse:
    image: docker.arvancloud.ir/clickhouse:lts-jammy
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9005:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: 123456
      CLICKHOUSE_DB: mydb
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

volumes:
  clickhouse_data:
  clickhouse_logs:
