version: '3.8'

services:
  # سرور k3s (control-plane + single node)
  k3s-server:
    image: rancher/k3s:v1.30.12-rc1-k3s1
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - k3s-data:/var/lib/rancher/k3s
      - ./output:/output
    ports:
      - "6443:6443"     # API سرور

  # کلاینت kubectl هماهنگ با نسخه سرور
  kubectl:
    image: docker.arvancloud.ir/bitnami/kubectl:1.30.12-debian-12-r0
    depends_on:
      - k3s-server
    volumes:
      - ./output/kubeconfig.yaml:/root/.kube/config:ro
    entrypoint: ["tail", "-f", "/dev/null"]
    # برای اجرای دستورات:
    # docker-compose run --rm kubectl kubectl get nodes

volumes:
  k3s-data:
